### ISSUE TITLE
TorSharpToolFetcher issue: The requested security protocol is not supported

### ISSUE THREAD

**Issue by AlizerUncaged** [joelverhagen/TorSharp#104]
I get the following error

```
System.NotSupportedException: The requested security protocol is not supported.
   at System.Net.ServicePointManager.ValidateSecurityProtocol(SecurityProtocolType value)
   at System.Net.ServicePointManager.set_SecurityProtocol(SecurityProtocolType value)
   at Knapcode.TorSharp.TorSharpToolFetcher.EnableSecurityProtocols() in /_/src/TorSharp/TorSharpToolFetcher.cs:line 229
```

here's my code, copied right from the ReadMe
```
    public async Task SetupTor()
    {
        _logger.LogInformation($"Downloading tor...");
        using (var httpClient = new HttpClient())
        {
            var fetcher = new TorSharpToolFetcher(_settings, httpClient);
            await fetcher.FetchAsync();
        }
    }
```

screenshot
![image](https://github.com/joelverhagen/TorSharp/assets/86959368/389ae3ff-e747-4d93-be16-ecd73f1ff52f)

I use .NET 7, my host OS is Windows 11 x64

**Comment by AlizerUncaged** [comment]
I was able to fix this by settings ``EnableSecurityProtocolsForFetcher`` to false in my `_settings_` following #28, however it seems 1.8.4 should resolve this issue but seems like the fallback doesn't work...?

**Comment by i-lamrani** [comment]
Hello your can resolve your issue by adding this parameters to the settings    EnableSecurityProtocolsForFetcher = false; 
and and use HttpClient with a handler that ignore ssl validations like this : 
   var handler = new HttpClientHandler();
        handler.ClientCertificateOptions = ClientCertificateOption.Manual;
        handler.ServerCertificateCustomValidationCallback = 
            (httpRequestMessage, cert, cetChain, policyErrors) =>
            {
                return true;
            };
        // download tools
        await new TorSharpToolFetcher(_settings, new HttpClient(handler)).FetchAsync();

**Comment by joelverhagen** [comment]
What platform is this occurring on? I would like to know:
OS version (Linux distribution and version if applicable)
.NET version (with `dotnet --info`)
