### ISSUE TITLE
Unable to assign the process to the job object

### ISSUE THREAD

**Issue by kerryjiang** [joelverhagen/TorSharp#14]
Hello, I encountered one exception when I tried to start the Tor. It seems I missed some files?

My OS: Windows 7 x64

Somebody have any idea about this issue?

Thanks in advance!
 

Knapcode.TorSharp.TorSharpException: Unable to assign the process to the job object. Error: The system cannot find the file specified.
   at Knapcode.TorSharp.Tools.VirtualDesktopToolRunner.AssociateWithJob(PROCESS_INFORMATION processInformation, Boolean throwOnError)
   at Knapcode.TorSharp.Tools.VirtualDesktopToolRunner.StartAsync(Tool tool)
   at Knapcode.TorSharp.TorSharpProxy.<ConfigureAndStartAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Knapcode.TorSharp.TorSharpProxy.<InitializeAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Knapcode.TorSharp.TorSharpProxy.<ConfigureAndStartAsync>d__9.MoveNext()

**Comment by kerryjiang** [comment]
Probably is it caused by Win 7  doesn't have the feature Vistual Desktop?

**Comment by joelverhagen** [comment]
I don't have a Windows 7 machine to test this right now, but that seems like a reasonable explanation. You can use `ToolRunnerType.Simple` ([source](
https://github.com/joelverhagen/TorSharp/blob/6d5454478604bb9c3f528609ea1db2a3e36535fc/TorSharp/TorSharpSettings.cs#L18-L22)).

**Comment by joelverhagen** [comment]
Could you provide a small project that reproduces the issue? I tried the sandbox .exe that's built by the repository and both `Simple` and `VirtualDesktop` tool runner types work fine on my Windows 7 VM.
