### ISSUE TITLE
System.IO.InvalidDataException: End of Central Directory record could not be found.

### ISSUE THREAD

**Issue by roikra** [joelverhagen/TorSharp#31]
On Centos7 the function ConfigureAndStartAsync() throws:
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwrite)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName)
   at Knapcode.TorSharp.TorSharpProxy.ExtractTool(Tool tool, Boolean reloadTool)
   at Knapcode.TorSharp.TorSharpProxy.Extract(ToolSettings toolSettings)
   at Knapcode.TorSharp.TorSharpProxy.InitializeAsync()
   at Knapcode.TorSharp.TorSharpProxy.ConfigureAndStartAsync()

Any idea how to fix it?

**Comment by joelverhagen** [comment]
Seems the same as https://github.com/joelverhagen/TorSharp/issues/30. Closing as duplicate.

**Comment by joelverhagen** [comment]
Also, I release a [1.8.6](https://www.nuget.org/packages/Knapcode.TorSharp/1.8.6) version to improve this error experience with better exception messages.
