### ISSUE TITLE
Cannot run Privoxy on Unknown OS and X64 architecture. OS description: Darwin 17.7.0 Darwin Kernel Version 17.7.0

### ISSUE THREAD

**Issue by roikra** [joelverhagen/TorSharp#41]
Getting the following error while trying to run the code from MaxOs:
Knapcode.TorSharp.TorSharpException: Cannot run Privoxy on Unknown OS and X64 architecture. OS description: Darwin 17.7.0 Darwin Kernel Version 17.7.0: Sun Jun  2 20:31:42 PDT 2019; root:xnu-4570.71.46~1/RELEASE_X86_64.
   at Knapcode.TorSharp.TorSharpSettings.RejectRuntime(String action)
   at Knapcode.TorSharp.ToolUtility.GetPrivoxyToolSettings(TorSharpSettings settings)
   at Knapcode.TorSharp.TorSharpToolFetcher.CheckForUpdatesAsync(Boolean allowExistingTools)
   at Knapcode.TorSharp.TorSharpToolFetcher.FetchAsync()
   at WebCrawler.MyTorProxy.ConfigureAndStartAsync() in /Users/roikrakovski/crawler/crawler/MyTorProxy.cs:line 82

**Comment by roikra** [comment]
I just saw that MacOS is not in the plan. Closing the issue.

**Comment by joelverhagen** [comment]
The main problem is that I don't have a Mac to test this on 😞. In theory it should work since both Prixovy and Tor has Mac OS binaries available on their distribution sites. I think the main things to figure out would be the extraction code for whatever archive format Mac OS uses and any `chmod +x` execution on the binaries if necessary. I'm actually going to re-open this so I know that there is interest in the Mac OS implementation.

**Comment by shekohex** [comment]
Just a Hacky workaround, set `OSPlatform` to `TorSharpOSPlatform.Linux` to just try it out.
